{% set version = "0.3.3" %}
{% set sha256 = "1033a326b55295e183f6a1283c9fbed47263903e8a14ec7048755db0d65c92ed" %}

package:
  name: xo
  version: {{ version }}

source:
  fn: xo-{{ sha256 }}.tar.gz
  url: https://github.com/scopatz/xo/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py2k]
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - urwid
    - pygments
    - pygments-cache

test:
  commands:
    - xo --help

about:
  home: http://exofrills.org/
  license: WTFPL v2
  summary: "exofrills text editor"

extra:
  recipe-maintainers:
    - scopatz
