{% set version = "0.3.1" %}
{% set sha256 = "b32ba2dfd43d53dcb544f089f5f57c30af090903a969017e2cffceccad30df22" %}

package:
  name: xo
  version: {{ version }}

source:
  fn: xo-{{ sha256 }}.tar.gz
  url: https://github.com/scopatz/xo/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py2k]
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - urwid
    - pygments
    - pygments-cache

test:
  commands:
    - xo --help

about:
  home: http://exofrills.org/
  license: WTFPL v2
  summary: "exofrills text editor"

extra:
  recipe-maintainers:
    - scopatz
