{% set version = "0.2.1" %}
{% set sha256 = "e31622e295faa134e2ee2fa4c8c30de3fbe940e15d8496519974001d1588c8b6" %}

package:
  name: xo
  version: {{ version }}

source:
  fn: xo-{{ sha256 }}.tar.gz
  url: https://github.com/scopatz/xo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py2k]
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - lazyasd
    - urwid
    - pygments

test:
  commands:
    - xo --help

about:
  home: http://exofrills.org/
  license: WTFPL v2
  summary: "exofrills text editor"

extra:
  recipe-maintainers:
    - scopatz
