{% set version = "0.3.3" %}
{% set sha256 = "1033a326b55295e183f6a1283c9fbed47263903e8a14ec7048755db0d65c92ed" %}

package:
  name: xo
  version: {{ version }}

source:
  url: https://github.com/scopatz/xo/releases/download/{{ version }}/xo-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - xo = xo:main

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - urwid
    - pygments
    - pygments-cache

test:
  commands:
    - xo --help

about:
  home: http://exofrills.org/
  license: WTFPL v2
  license_family: OTHER
  summary: "exofrills text editor"

extra:
  recipe-maintainers:
    - scopatz
