travis:
  secure:
    BINSTAR_TOKEN: AFVzxpiviXtupwM+l0020i/8lgJ9ifnk24zOXa48SWQQ5nijQmYLUXayN55dmm4ws7GJo9JaSBioo13R2LwlRgIqctsQNCNaZbZ4r7anh/wZEYLMUQTgN3jeuaIeESu8U/6oo0FX16aY/2+NM83geXO8US98fXK1oaq0AzGHRZOl/2PZuawDGW8zGaX0pchK+A6zKcH4cM62xbJsd5I7BEbGkKeBFFpLbVHrACZuRZ4KCYbX9ZYkVVGRFP1SNem/6XuUatkmdMKdYh+1NM/Cgu0wDFoCM/EqfonNlbsfjl/FXkt12fUPPY5Q/lQ1AXqgDd+XUhIiS9Yg4hrsoftiTM5iYEcPtUaScXVAMiZYdghlH/VPEKnX/PZxBX5wbKWgQt4N1lmCsEedPiBtFV/od+PIyZiD7T+j10yEEUw8yDU1SSeuAvXD6aAAEfrReww4jLDKA9TlZZ7fsE9eaBQjMaTwpuFwBnlb8vzGEd1rcgJvFP5zD07HdZCtEk4qjpXEBghSPfe6Ns1OVo4WEOBU1ykgdraJkyW1LbMSVYMUbDPO8GHEeWT5vjkyuglPf4vpdQnb0DGqgHbmDkwQLDs/koyVER4ZLVdv7upfmWBos37B0IvCb65qCT9CJ7rteoMCP0JoZfpBw8CJSRIeXzgW1Lb3nwNOFK/1qIYRMGuutC8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
